---
- name: Deploy Application on Multiple Servers
  hosts: all
  vars_prompt:
    - name: username
      prompt: "Enter the username for deploying the application"
      private: no
    - name: appname
      prompt: "Enter the name of the application"
      private: no
    - name: url
      prompt: "Enter the URL to download the application package"
      private: no
  become: yes
  tasks:
    - name: Create new user
      user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes

    - name: Download package from URL
      get_url:
        url: "{{ url }}"
        dest: "/home/{{ username }}/{{ appname }}.tar.gz"

    - name: Extract package
      unarchive:
        src: "/home/{{ username }}/{{ appname }}.tar.gz"
        dest: "/home/{{ username }}"
        remote_src: yes

    - name: Start application
      shell: "/home/{{ username }}/{{ appname }}/{{ appname }}.sh &"